name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: samsonjs/deploy-action@v1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          remote-path: ${{ secrets.DEPLOY_PATH }}
          args: rsync -av --delete .next/ /var/www/portfolio/.next/
